package com.example.lawyerly.model

import com.example.lawyerly.R
import java.util.*

class LawyerRepository {

    val lawyers = listOf(
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            50.76f,
            4.5f,
            true,
            R.drawable.image1,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            80.73f,
            3.8f,
            false,
            R.drawable.image2,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            60.80f,
            4.9f,
            true,
            R.drawable.image3,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            20.76f,
            2.5f,
            true,
            R.drawable.image4,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            80.74f,
            4.2f,
            false,
            R.drawable.image5,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            35.56f,
            3.2f,
            true,
            R.drawable.image1,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            90.94f,
            3.5f,
            false,
            R.drawable.image2,
            true,
            Date(),
            14,
            "1/18",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            70.76f,
            4.1f,
            false,
            R.drawable.image3,
            true,
            Date(),
            14,
            "1/18",
            1,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            40.76f,
            4.7f,
            true,
            R.drawable.image4,
            true,
            Date(),
            10,
            "1/120",
            2,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        ),
        Lawyer(
            "Name",
            "Surname",
            "Speciality",
            56.76f,
            4.0f,
            true,
            R.drawable.image5,
            true,
            Date(),
            24,
            "1/13",
            1,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        )
    )

}